// This file is auto-generated by @hey-api/openapi-ts

export { getCountGames, healthCheck, type Options, postAnalyze, postBotMove, postNextStates } from './sdk.gen';
export type { AnalyzeRequest, AnalyzeResponse, BotMoveRequest, BotMoveResponse, ClientOptions, CountGamesResponse, GetCountGamesData, GetCountGamesResponse, GetCountGamesResponses, HealthCheckData, HealthCheckResponses, HttpValidationError, NextStatesRequest, NextStatesResponse, PostAnalyzeData, PostAnalyzeError, PostAnalyzeErrors, PostAnalyzeResponse, PostAnalyzeResponses, PostBotMoveData, PostBotMoveError, PostBotMoveErrors, PostBotMoveResponse, PostBotMoveResponses, PostNextStatesData, PostNextStatesError, PostNextStatesErrors, PostNextStatesResponse, PostNextStatesResponses, ValidationError } from './types.gen';
