// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetCountGamesData, GetCountGamesErrors, GetCountGamesResponses, HealthCheckData, HealthCheckResponses, PostAnalyzeData, PostAnalyzeErrors, PostAnalyzeResponses, PostBotMoveData, PostBotMoveErrors, PostBotMoveResponses, PostEvaluateData, PostEvaluateErrors, PostEvaluateResponses, PostNextStatesData, PostNextStatesErrors, PostNextStatesResponses, PostStatsData, PostStatsErrors, PostStatsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Post Analyze
 */
export const postAnalyze = <ThrowOnError extends boolean = false>(options: Options<PostAnalyzeData, ThrowOnError>) => (options.client ?? client).post<PostAnalyzeResponses, PostAnalyzeErrors, ThrowOnError>({
    url: '/analyze',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post Next States
 */
export const postNextStates = <ThrowOnError extends boolean = false>(options: Options<PostNextStatesData, ThrowOnError>) => (options.client ?? client).post<PostNextStatesResponses, PostNextStatesErrors, ThrowOnError>({
    url: '/next-states',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post Evaluate
 */
export const postEvaluate = <ThrowOnError extends boolean = false>(options: Options<PostEvaluateData, ThrowOnError>) => (options.client ?? client).post<PostEvaluateResponses, PostEvaluateErrors, ThrowOnError>({
    url: '/evaluate',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Count Games
 */
export const getCountGames = <ThrowOnError extends boolean = false>(options?: Options<GetCountGamesData, ThrowOnError>) => (options?.client ?? client).get<GetCountGamesResponses, GetCountGamesErrors, ThrowOnError>({ url: '/count-games', ...options });

/**
 * Post Bot Move
 */
export const postBotMove = <ThrowOnError extends boolean = false>(options: Options<PostBotMoveData, ThrowOnError>) => (options.client ?? client).post<PostBotMoveResponses, PostBotMoveErrors, ThrowOnError>({
    url: '/bot-move',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Post Stats
 */
export const postStats = <ThrowOnError extends boolean = false>(options: Options<PostStatsData, ThrowOnError>) => (options.client ?? client).post<PostStatsResponses, PostStatsErrors, ThrowOnError>({
    url: '/stats',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Health Check
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({ url: '/health', ...options });
