// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AnalyzeRequest
 */
export type AnalyzeRequest = {
    /**
     * Board
     */
    board: string;
};

/**
 * AnalyzeResponse
 */
export type AnalyzeResponse = {
    /**
     * Score
     */
    score: number | null;
};

/**
 * BotMoveRequest
 */
export type BotMoveRequest = {
    /**
     * Board
     */
    board: string;
    /**
     * Difficulty
     */
    difficulty?: 'easy' | 'hard';
};

/**
 * BotMoveResponse
 */
export type BotMoveResponse = {
    /**
     * Board
     */
    board: string;
};

/**
 * CountGamesResponse
 */
export type CountGamesResponse = {
    /**
     * Count
     */
    count: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * NextStatesRequest
 */
export type NextStatesRequest = {
    /**
     * Board
     */
    board: string;
};

/**
 * NextStatesResponse
 */
export type NextStatesResponse = {
    /**
     * Next States
     */
    next_states: Array<string>;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type PostAnalyzeData = {
    body: AnalyzeRequest;
    path?: never;
    query?: never;
    url: '/analyze';
};

export type PostAnalyzeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostAnalyzeError = PostAnalyzeErrors[keyof PostAnalyzeErrors];

export type PostAnalyzeResponses = {
    /**
     * Successful Response
     */
    200: AnalyzeResponse;
};

export type PostAnalyzeResponse = PostAnalyzeResponses[keyof PostAnalyzeResponses];

export type PostNextStatesData = {
    body: NextStatesRequest;
    path?: never;
    query?: never;
    url: '/next-states';
};

export type PostNextStatesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostNextStatesError = PostNextStatesErrors[keyof PostNextStatesErrors];

export type PostNextStatesResponses = {
    /**
     * Successful Response
     */
    200: NextStatesResponse;
};

export type PostNextStatesResponse = PostNextStatesResponses[keyof PostNextStatesResponses];

export type GetCountGamesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/count-games';
};

export type GetCountGamesResponses = {
    /**
     * Successful Response
     */
    200: CountGamesResponse;
};

export type GetCountGamesResponse = GetCountGamesResponses[keyof GetCountGamesResponses];

export type PostBotMoveData = {
    body: BotMoveRequest;
    path?: never;
    query?: never;
    url: '/bot-move';
};

export type PostBotMoveErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostBotMoveError = PostBotMoveErrors[keyof PostBotMoveErrors];

export type PostBotMoveResponses = {
    /**
     * Successful Response
     */
    200: BotMoveResponse;
};

export type PostBotMoveResponse = PostBotMoveResponses[keyof PostBotMoveResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
